### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by ARealDD** [yiranyyu/BUAA-SE-OS-summary#1]
文中写：GDT中的基地址是物理地址，LDT中的基地址是线性地址。
是否意味着，无论是否开启分页机制，GDT中的段空间都不经过分页映射？

**Comment by yiranyyu** [comment]
段应该只是一个逻辑概念，具体如何利用 GDT 和 LDT 进行寻址我想[实验 7](https://www.shiyanlou.com/courses/1377) 中应该已经介绍的非常详细了，你可以参考一下。这里我大概整理一下：

1. 通过 GDTR 获取 GDT 的基地址（物理地址）
2. 通过 LDTR 和刚才获得的 GDT 基地址获取 LDT 表的段描述符的物理地址
3. 通过访问段寄存器获取对应段的选择子，从而得到段描述符在 LDT 或者 GDT 中的偏移
4. 利用已经获得的这些物理地址和上一步获取到的偏移就可以获取到需要访问的描述符的物理地址
5. 利用描述符中的内容获取到线性地址
6. 利用线性地址进一步寻址，这是就要根据是否分页有不同的处理
